# Generated by Django 2.2.6 on 2019-11-04 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_setor', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Etapa')),
            ],
        ),
    ]
